name: OPA Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: v0.46.1  # Specify a known good version

      - name: Verify OPA Installation
        run: opa version

      - name: Validate Policies
        run: opa check policies/
